--- #YAML:1.0
name:                Device-SpaceNavigator
version:             0.02
abstract:            Read data from 3Dconnexion SpaceNavigator
license:             perl
author:              
    - Kay Bærulfsen <kaysb@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
